name: Post Morning
on: { schedule: [ { cron: "30 22 * * *" } ], workflow_dispatch: {} }  # 07:30 JST
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
      - name: Pick oldest md
        id: pick
        run: |
          f=$(ls -1 content/morning/*.md 2>/dev/null | head -n 1 || true)
          if [ -z "$f" ]; then echo "no_file=true" >> $GITHUB_OUTPUT; exit 0; fi
          echo "file=$f" >> $GITHUB_OUTPUT
      - name: Render
        if: steps.pick.outputs.no_file != 'true'
        run: |
          python scripts/render.py "${{ steps.pick.outputs.file }}"
      - name: Archive
        if: steps.pick.outputs.no_file != 'true'
        run: |
          mkdir -p content/posted
          git mv "${{ steps.pick.outputs.file }}" content/posted/ || true
          git add -A && git commit -m "posted: ${{ steps.pick.outputs.file }}" || true
          git push || true
